### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by SzalikDesigns** [anthonycaccese/es-theme-airen#2]
# For you

- [x] Can you make the "-system" a little bit darker as you did on the artbook - so the logos will be better represented
- [x] Can you make clock wifi/battery font just white like (game counter/logos) please :)
- [x] When you select the video option there is still all metadata information and the "gamelist-metadata" is used instead of "gamelist-video". Im not sure if this was on purpose or it was planned to look like this 

![image](https://user-images.githubusercontent.com/77732736/111882228-69f55c80-89ac-11eb-9a7e-f08b1b0ebc7c.png)

![image](https://user-images.githubusercontent.com/77732736/111882061-5b5a7580-89ab-11eb-8a90-67ddc28f1eb7.png)

---

### For me todo:

**missing logo for:**
* vertical arcade
* 2 players
* 4 players
* never played
* retroachievements 

----------------------

### the ones already made:

**Other features missing:**
- [x] add the transparent block line for battery / wi-fi

**wrong logo:**
- [x] sinclair zx81

**missing logo for:**
- [x] tools
- [x] Nintendo Entertainment System **(Hacks)**
- [x] Game Gear **( Hacks )**

**there is no background for:**
- [x] Gamelist view style - automatic
- [x] Gamelist view style - basic

**Comment by anthonycaccese** [comment]
Re: there is no background for:
Gamelist view style - automatic
Gamelist view style - basic
Gamelist view style - grid

You will need to create a design for the basic view.  Lemfiggity did not create one so I have nothing to work from on it.  Grid will not be supported in this design I think so I am not sure that matters to support.  Automatic has a background if its using detailed or video view.  Automatic can not be styled directly.  So the open item here is a design for basic view

**Comment by anthonycaccese** [comment]
re missing logo for:
 Nintendo Entertainment System (Hacks)
 Game Gear ( Hacks )
 vertical arcade
 2 players
 4 players
 never played
 retroachievements

I am not planning to make logos for these but if you would like to I am glad to add them.  SVG format is preferred.

**Comment by anthonycaccese** [comment]
Re: Other features missing
 remove the game count on bottom
 add the transparent block line for battery / wi-fi
 move the battery / wifi to the right corner as it is on the art-theme
 add clock on left side please ? : )

I'll work on these this weekend

**Comment by anthonycaccese** [comment]
i added layout for basic
updated zx81 logo
added transparent bar

still needs a lot of work though
