### ISSUE TITLE
Game List w/Metadata showing reversed images

### ISSUE THREAD

**Issue by bmn001** [anthonycaccese/es-theme-airen#4]
I have two images for each rom:
2D Boxart stored in /images
A screenshot stored in /screenshots
(I'm not using videos.)

I want to configure the theme to look like this demo image:
https://camo.githubusercontent.com/19f6d41ab6aea987cf411470680370c80fe8ea605326b11ff19ea39f659c136a/68747470733a2f2f692e696d6775722e636f6d2f30366c515051412e706e67

However it's showing the boxart as the background image, and the screenshot as the tiny foreground image, which is the opposite of the sample image :)

The hacky solution is for me to rename /images to /screenshots and vice versa, but that's a bit counterintuitive and indicates maybe it's a bug in the theme?

I realize I'm using the "Video" gamelist view style without videos, but it's the only way to get both images to display.  Shouldn't the 2d box art be showing up in the right spot, at least?

**Comment by anthonycaccese** [comment]
Hi @bmn001 can you provide a sample of your gamelist.xml?  The issue may be related to how the images are mapped in that file.

**Comment by bmn001** [comment]
It's very possible I screwed something up somewhere...

My gamelist.xml was generated by Skraper.
It put boxart in /images/ and screenshots in /screenshot/

Here's part of my gamelist.xml:

```
<game id="3769" source="ScreenScraper.fr">
<path>./Metroid - Zero Mission (USA).zip</path>
<name>Metroid : Zero Mission</name>
<desc>She's battled baddies on nearly every Nintendo system, and now, Samus Aran returns to her roots. Metroid: Zero Mission relives the story that started it all--revealing for the first time full details of her meeting with the Metroids. The plotline will be familiar to longtime fans of the Metroid series, but the challenges are new, the power-ups are plentiful, and the graphics and sound are supercharged. Plus, if you thought that the original Metroid had a surprise ending, wait until you get past the Mother Brain in Metroid: Zero Mission. A new twist provides a deeper adventure than ever before.</desc>
<rating>0.9</rating>
<releasedate>20040209T000000</releasedate>
<developer>Nintendo</developer>
<publisher>Nintendo</publisher>
<genre>Platform-Action-Action / Adventure-Race, Driving</genre>
<players>1</players>
<hash>5C61A844</hash>
<image>./images/Metroid - Zero Mission (USA).png</image>
<thumbnail>./screenshot/Metroid - Zero Mission (USA).png</thumbnail>
<genreid>257</genreid>
</game>
```
And here's what I'm seeing:

![rg351p](https://user-images.githubusercontent.com/4766836/122596746-2a77f400-d01f-11eb-8a9b-a13508eacdd3.jpg)

**Comment by bmn001** [comment]
Well I'm not sure what the problem is, so for now I've just renamed my images and screenshot directories across all systems.

This seems to work great. I'll just have to remember to change then back again if I ever re-scrape.

**Comment by SzalikDesigns** [comment]
i think you scrapped them uncorrect way, if it make sense as i can't reproduce
